version: '2'
services:
  rancher-medieval-webserver:
    cap_add:
    - SYS_PTRACE
    image: stevenmunro/hosting:new
    sysctls:
      net.core.somaxconn: '32768'
      net.ipv4.tcp_syncookies: '0'
    environment:
      - DOMAIN=${DOMAIN}
      - ENABLE_OP_CACHE=${ENABLE_OP_CACHE}
      - ENABLE_APCU_CACHE=${ENABLE_APCU_CACHE}
      - ENABLE_WP_ROCKET=${ENABLE_WP_ROCKET}
      - ENABLE_BASIC_AUTH=${ENABLE_BASIC_AUTH}
      - AUTH=${AUTH}
      - PHP_VERSION=${PHP_VERSION}
      - PHP_MAX_CHILDREN=${PHP_MAX_CHILDREN}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - APC_SHM_SIZE=${APC_SHM_SIZE}
      - WORDPRESS=${WORDPRESS}
      - HTTPS=${LE_TEST}
      - OVERRIDE_DBPASS=${DBPASS}
    stdin_open: true

    links:
    - rancher-medieval-database:database

    volumes:
    - /nfsshare/${DIRECTORY}:/DATA
    # secrets:
    # - mode: '0444'
    #   uid: '0'
    #   gid: '0'
    #   source: pushbullet
    #   target: pushbullet
    secrets:
    - mode: 444
      uid: '0'
      gid: '0'
      source: pushbullet
      target: ''
    tty: true
    cpu_shares: 2000
    labels:
      rap.port: '80'
      io.rancher.scheduler.affinity:host_label: host=${WEBHOST}
      {{- if eq .Values.LE_HOST "" }}
      rap.https_method: nohttps
      {{- else }}
      rap.le_host: ${LE_HOST}
      rap.le_test: ${LE_TEST}
      rap.https_method: redirect
      {{- end }}
      io.rancher.container.pull_image: always
      rap.host: ${DOMAINS}
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment

  rancher-medieval-database:
      image: mariadb:10.2
      command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_allowed_packet=500M
      - --innodb_buffer_pool_size=64M
      - --innodb_flush_log_at_trx_commit=2
      - --innodb_log_file_size=64M
      - --innodb_flush_method=O_DIRECT
      - --innodb_autoinc_lock_mode=2
      - --innodb_flush_neighbors=0
      - --innodb_random_read_ahead=OFF
      - --innodb_io_capacity=2000
      - --innodb_io_capacity_max=4000
      - --innodb_file_per_table=1
      - --max_connections=100
      - --skip_name_resolve=ON
      
      sysctls:
        net.core.somaxconn: '32768'
        net.ipv4.tcp_syncookies: '0'
      environment:
        - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysqlroot
        #- MYSQL_ROOT_PASSWORD=abc123
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=wordpress
        - MYSQL_PASSWORD=wordpress
      stdin_open: true
      volumes:
      - /nfsshare/${DIRECTORY}/mariadb/mysql:/var/lib/mysql
      # ports:
      # - ${DBPORT}:3306
      secrets:
      - mode: 444
        uid: '0'
        gid: '0'
        source: mysqlroot
        target: mysqlroot
      tty: true
      labels:
        io.rancher.scheduler.affinity:host_label: host=${DBHOST}
        io.rancher.container.pull_image: always
        io.rancher.container.create_agent: 'true'
        io.rancher.container.agent.role: environment


secrets:
  pushbullet:
    external: 'true'
  mysqlroot:
    external: 'true'