name: Rancher Medieval Webserver Service
description: |
  Hosting Service
version: 0.1.4
category: Applications
maintainer: Medieval <info@medievalwp.co.nz>
license: MIT
projectURL: https://github.com/stevenmunro/rancher-medieval