version: '2'
services:
  rancher-medieval-database:
    image: percona:5.7
    command: mysqld --max_allowed_packet=500M --innodb_buffer_pool_size=3G --innodb_flush_log_at_trx_commit=2 --innodb_flush_log_at_timeout=5 --innodb_log_file_size=512M --innodb_flush_method=O_DIRECT --innodb_autoinc_lock_mode=2 --sync_binlog=0 --innodb_doublewrite=1 --innodb_buffer_pool_instances=8 --innodb_change_buffering=none --innodb_adaptive_hash_index=OFF --innodb_flush_neighbors=0 --innodb_read_io_threads=8 --innodb_write_io_threads=8 --innodb_lru_scan_depth=8192 --innodb_io_capacity=15000 --innodb_io_capacity_max=25000 --loose-innodb-page-cleaners=4 --table_open_cache_instances=64 --table_open_cache=5000 --loose-innodb-log_checksum-algorithm=crc32 --loose-innodb-checksum-algorithm=strict_crc32 --max_connections=50000 --skip_name_resolve=ON --loose-performance_schema=ON --loose-performance-schema-instrument='wait/synch/%=ON'
    sysctls:
      net.core.somaxconn: '32768'
      net.ipv4.tcp_syncookies: '0'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    stdin_open: true
    volumes:
    - ${DATADIR}:/var/lib/mysql
    ports:
      - ${PORT}:3306
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: host=${HOST}
      io.rancher.container.pull_image: always
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
