version: '2'
services:
  rancher-medieval-database:
    image: percona:5.7
    command: mysqld --max_allowed_packet=500M --innodb_file_per_table=1 --innodb_buffer_pool_size=1G --thread_cache_size=16 --skip-name-resolve --query_cache_size=64M --tmp_table_size=64M --max_heap_table_size=64M --wait_timeout=60 --max_heap_table_size=64M --read_buffer_size=64M --read_rnd_buffer_size=64M --sort_buffer_size=64M --join_buffer_size=64M --thread_stack=192K --key_buffer=64M
    sysctls:
      net.core.somaxconn: '32768'
      net.ipv4.tcp_syncookies: '0'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    stdin_open: true
    volumes:
    - ${DATADIR}:/var/lib/mysql
    ports:
      - ${PORT}:3306
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: host=${HOST}
      io.rancher.container.pull_image: always
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
