version: '2'
services:
  rancher-medieval-dbcluster:
    image: percona:percona-xtradb-cluster
    command:
    - mysqld
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --max_allowed_packet=500M
    - --innodb_buffer_pool_size=128M
    - --innodb_flush_log_at_trx_commit=2
    - --innodb_flush_log_at_timeout=5
    - --innodb_log_file_size=64M
    - --innodb_flush_method=O_DIRECT
    - --innodb_autoinc_lock_mode=2
    - --sync_binlog=0
    - --innodb_doublewrite=1
    - --innodb_buffer_pool_instances=8
    - --innodb_change_buffering=none
    - --innodb_adaptive_hash_index=OFF
    - --innodb_flush_neighbors=0
    - --innodb_read_io_threads=8
    - --innodb_write_io_threads=8
    - --innodb_lru_scan_depth=8192
    - --innodb_io_capacity=15000
    - --innodb_io_capacity_max=25000
    - --loose-innodb-page-cleaners=4
    - --table_open_cache_instances=64
    - --table_open_cache=5000
    - --loose-innodb-checksum-algorithm=strict_crc32
    - --max_connections=50000
    - --skip_name_resolve=ON
    - --loose-performance_schema=ON
    - --loose-performance-schema-instrument=wait/synch/%=ON
    - --plugin-load=audit_log=audit_log.so
    - --audit_log_format=CSV
    - --audit_log_file=audit.log
    
    sysctls:
      net.core.somaxconn: '32768'
      net.ipv4.tcp_syncookies: '0'
    environment:
      #- MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysqlroot
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    stdin_open: true
    volumes:
    - /percona-test/mysql:/var/lib/mysql
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: host=${DBHOST}
      io.rancher.container.pull_image: always
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
