version: '2'
services:
  rancher-medieval:
    mem_limit: 469762048
    image: stevenmunro/hosting:new
    sysctls:
      net.core.somaxconn: '32768'
      #net.core.netdev_max_backlog: '32768'
      #net.ipv4.tcp_max_syn_backlog: '4096'
      net.ipv4.tcp_tw_recycle: '0'
      net.ipv4.tcp_tw_reuse: '0'
      net.ipv4.tcp_fin_timeout: '7'
      #net.core.rmem_max: '16777216'
      #net.core.wmem_max: '16777216'
      net.ipv4.tcp_rmem: '8192 87380 16777216'
      net.ipv4.tcp_wmem: '8192 65536 16777216'
      net.ipv4.ip_local_port_range: '1024 65535'
      #net.ipv4.tcp_timestamps: '1'
    environment:
      - DOMAIN=${DOMAIN}
      - DISABLE_OP_CACHE=${DISABLE_OP_CACHE}
      - DISABLE_NGINX_CACHE=${DISABLE_NGINX_CACHE}
      - PHP_VERSION=${PHP_VERSION}
    stdin_open: true
    external_links:
    - Caching/memcached:memcached
    volumes:
    - /nfsshare/${DOMAIN}:/DATA
    tty: true
    memswap_limit: 536870912
    cpu_shares: 200
    labels:
      rap.port: '80'
      io.rancher.scheduler.affinity:host_label: host=${HOST}
      rap.le_host: ${LE_HOST}
      rap.le_test: ${LE_TEST}
      rap.https_method: ${HTTPS_METHOD}
      io.rancher.container.pull_image: always
      rap.host: ${DOMAINS}
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
