version: '2'
services:
  rancher-medieval-webserver:
    cap_add:
    - SYS_PTRACE
    image: stevenmunro/hosting:new
    sysctls:
      net.core.somaxconn: '32768'
      net.ipv4.tcp_syncookies: '0'
    environment:
      - DOMAIN=${DOMAIN}
      - ENABLE_OP_CACHE=${ENABLE_OP_CACHE}
      - ENABLE_APCU_CACHE=${ENABLE_APCU_CACHE}
      - ENABLE_NGINX_CACHE=${ENABLE_NGINX_CACHE}
      - ENABLE_BASIC_AUTH=${ENABLE_BASIC_AUTH}
      - AUTH=${AUTH}
      - PHP_VERSION=${PHP_VERSION}
      - PHP_MAX_CHILDREN=${PHP_MAX_CHILDREN}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - APC_SHM_SIZE=${APC_SHM_SIZE}
      - WORDPRESS_DB_HOST=rancher-medieval-database:3306
    stdin_open: true
    external_links:
    - Caching/memcached:memcached
    volumes:
    - /nfsshare/${DOMAIN}:/DATA
    tty: true
    cpu_shares: 2000
    labels:
      rap.port: '80'
      io.rancher.scheduler.affinity:host_label: host=${HOST}
      rap.le_host: ${LE_HOST}
      rap.le_test: ${LE_TEST}
      rap.https_method: ${HTTPS_METHOD}
      io.rancher.container.pull_image: always
      rap.host: ${DOMAINS}
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
      io.rancher.sidekicks: rancher-medieval-database

  rancher-medieval-database:
      image: percona:5.7
      command: mysqld --max_allowed_packet=500M --innodb_buffer_pool_size=128M --innodb_flush_log_at_trx_commit=2 --innodb_flush_log_at_timeout=5 --innodb_log_file_size=64M --innodb_flush_method=O_DIRECT --innodb_autoinc_lock_mode=2 --sync_binlog=0 --innodb_doublewrite=1 --innodb_buffer_pool_instances=8 --innodb_change_buffering=none --innodb_adaptive_hash_index=OFF --innodb_flush_neighbors=0 --innodb_read_io_threads=8 --innodb_write_io_threads=8 --innodb_lru_scan_depth=8192 --innodb_io_capacity=15000 --innodb_io_capacity_max=25000 --loose-innodb-page-cleaners=4 --table_open_cache_instances=64 --table_open_cache=5000 --loose-innodb-log_checksum-algorithm=crc32 --loose-innodb-checksum-algorithm=strict_crc32 --max_connections=50000 --skip_name_resolve=ON --loose-performance_schema=ON --loose-performance-schema-instrument='wait/synch/%=ON'
      sysctls:
        net.core.somaxconn: '32768'
        net.ipv4.tcp_syncookies: '0'
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=wordpress
        - MYSQL_PASSWORD=wordpress

      stdin_open: true
      volumes:
      - /nfsshare/${DOMAIN}/percona/mysql:/var/lib/mysql
      ports:
        - ${DATABASE_PORT}:3306/tcp
      tty: true
      labels:
        io.rancher.scheduler.affinity:host_label: host=${HOST}
        io.rancher.container.pull_image: always
        io.rancher.container.create_agent: 'true'
        io.rancher.container.agent.role: environment
