version: '2'
services:
  rancher-medieval-webserver:
    cap_add:
    - SYS_PTRACE
    image: stevenmunro/hosting:new
    sysctls:
      net.core.somaxconn: '32768'
      net.ipv4.tcp_syncookies: '0'
    environment:
      - DOMAIN=${DOMAIN}
      - ENABLE_OP_CACHE=${ENABLE_OP_CACHE}
      - ENABLE_NGINX_CACHE=${ENABLE_NGINX_CACHE}
      - ENABLE_BASIC_AUTH=${ENABLE_BASIC_AUTH}
      - AUTH=${AUTH}
      - PHP_VERSION=${PHP_VERSION}
      - PHP_MAX_CHILDREN=${PHP_MAX_CHILDREN}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
    stdin_open: true
    external_links:
    - Caching/memcached:memcached
    volumes:
    - /nfsshare/${DOMAIN}:/DATA
    tty: true
    cpu_shares: 200
    labels:
      rap.port: '80'
      io.rancher.scheduler.affinity:host_label: host=${HOST}
      rap.le_host: ${LE_HOST}
      rap.le_test: ${LE_TEST}
      rap.https_method: ${HTTPS_METHOD}
      io.rancher.container.pull_image: always
      rap.host: ${DOMAINS}
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
