version: '2'
services:
  rancher-medieval-webserver:
    cap_add:
    - SYS_PTRACE
    image: stevenmunro/hosting:new
    sysctls:
      net.core.somaxconn: '32768'
      net.ipv4.tcp_syncookies: '0'
    environment:
      - DOMAIN=${DOMAIN}
      - ENABLE_OP_CACHE=${ENABLE_OP_CACHE}
      - ENABLE_APCU_CACHE=${ENABLE_APCU_CACHE}
      - ENABLE_NGINX_CACHE=${ENABLE_NGINX_CACHE}
      - ENABLE_BASIC_AUTH=${ENABLE_BASIC_AUTH}
      - AUTH=${AUTH}
      - PHP_VERSION=${PHP_VERSION}
      - PHP_MAX_CHILDREN=${PHP_MAX_CHILDREN}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - APC_SHM_SIZE=${APC_SHM_SIZE}
      - WORDPRESS=${WORDPRESS}
      - HTTPS=${LE_TEST}
    stdin_open: true
    external_links:
    - Caching/memcached:memcached
    links:
    - rancher-medieval-database:database
    volumes:
    - /nfsshare/${DIRECTORY}:/DATA
    # secrets:
    # - mode: '0444'
    #   uid: '0'
    #   gid: '0'
    #   source: pushbullet
    #   target: pushbullet
    secrets:
    - mode: 444
      uid: '0'
      gid: '0'
      source: pushbullet
      target: ''
    tty: true
    cpu_shares: 2000
    labels:
      rap.port: '80'
      io.rancher.scheduler.affinity:host_label: host=${WEBHOST}
      rap.le_host: ${LE_HOST}
      rap.le_test: ${LE_TEST}
      rap.https_method: ${HTTPS_METHOD}
      io.rancher.container.pull_image: always
      rap.host: ${DOMAINS}
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment

  rancher-medieval-database:
      image: percona:5.7
      command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_allowed_packet=500M
      - --innodb_buffer_pool_size=20M
      - --innodb_flush_log_at_trx_commit=2
      - --innodb_log_file_size=64M
      - --innodb_flush_method=O_DIRECT
      - --innodb_autoinc_lock_mode=2
      - --innodb_flush_neighbors=0
      - --innodb_random_read_ahead=OFF
      - --innodb_io_capacity=2000
      - --innodb_io_capacity_max=4000
      - --max_connections=100
      - --skip_name_resolve=ON
      - --plugin-load=audit_log=audit_log.so
      - --audit_log_format=CSV
      - --audit_log_file=audit.log
      - --audit_log_rotate_on_size=512M
      - --audit_log_rotations=2
      
      sysctls:
        net.core.somaxconn: '32768'
        net.ipv4.tcp_syncookies: '0'
      environment:
        - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysqlroot
        #- MYSQL_ROOT_PASSWORD=abc123
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=wordpress
        - MYSQL_PASSWORD=wordpress
      stdin_open: true
      volumes:
      - /nfsshare/${DIRECTORY}/percona/mysql:/var/lib/mysql
      ports:
      - ${DBPORT}:3306
      secrets:
      - mode: 444
        uid: '0'
        gid: '0'
        source: mysqlroot
        target: mysqlroot
      tty: true
      labels:
        io.rancher.scheduler.affinity:host_label: host=${DBHOST}
        io.rancher.container.pull_image: always
        io.rancher.container.create_agent: 'true'
        io.rancher.container.agent.role: environment

secrets:
  pushbullet:
    external: 'true'
  mysqlroot:
    external: 'true'