name: Rancher Medieval Redirection Service
description: |
  Redirection Service
version: 0.1.7
category: Applications
maintainer: Medieval <info@medievalwp.co.nz>
license: MIT
projectURL: https://github.com/stevenmunro/rancher-medieval